services:
  dlhd-proxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
        API_URL: ${API_URL}
        PROXY_CONTENT: ${PROXY_CONTENT}
        SOCKS5: ${SOCKS5}
    environment:
      - PORT=${PORT}
      - API_URL=${API_URL}
      - PROXY_CONTENT=${PROXY_CONTENT}
      - SOCKS5=${SOCKS5}
      - TZ=${TZ}
      - GUIDE_UPDATE=${GUIDE_UPDATE}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
